server:
  port: 8080

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:5174"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
      routes:
        - id: admin-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/admin/jobs/**
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/auth/**
        - id: job-search-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/jobs/**
        - id: job-posting-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/job-posting/**
        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/alerts/**
        - id: ai-agent-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/v1/ai/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG