server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: admin-service
          uri: https://four458finaladminservice.onrender.com
          predicates:
            - Path=/api/v1/admin/jobs/**
        - id: auth-service
          uri: https://four458finaladminservice.onrender.com
          predicates:
            - Path=/api/v1/auth/**
        - id: job-search-service
          uri: https://four458finaljobsearchservice.onrender.com
          predicates:
            - Path=/api/v1/jobs/**
        - id: job-posting-service
          uri: https://four458finaljobpostingservice.onrender.com
          predicates:
            - Path=/api/v1/job-posting/**
        - id: notification-service
          uri: https://four458finalnotificationservice.onrender.com
          predicates:
            - Path=/api/v1/alerts/**
        - id: ai-agent-service
          uri: https://four458finalaiagentservice.onrender.com
          predicates:
            - Path=/api/v1/ai/**
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG